language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
  - '5'
  - '4'
script:
  - npm test
after_success:
  - npm run semantic-release
branches:
  only:
    - master
